refactor: страница редактирования профиля
Rullflex/on-the-way pull request #56
Opened 2024-07-12 11:03 UTC by NOGAVADU

2024-07-12 11:05 UTC, Rullflex commented on src/pages/profile/edit/index.vue
> +import ProfileEditDialog from 'pages/profile/edit/ui/ProfileEditDialog.vue';
относительные пути делай для местных импотов

2024-07-12 11:08 UTC, Rullflex commented on src/pages/profile/edit/index.vue
> +}
а почему тут расстояние изменились?

2024-07-12 11:08 UTC, NOGAVADU commented on src/pages/profile/edit/index.vue
> +}
Не расстояние, а я скобки добавил. Без них у меня почему-то постоянно слетал layout

2024-07-12 11:25 UTC, NOGAVADU commented
Это все замечания? Можно коммит с исправлениями отправлять? Или перезаписать этот лучше?

2024-07-12 11:34 UTC, Rullflex requested changes
Проверил. Кидай коммит с изменениями, не надо закрывать пул реквест

2024-07-12 11:34 UTC, Rullflex commented on src/pages/profile/edit/index.vue
> +fallbackRoute: '/profile'
запятых в конце не хватает

2024-07-12 11:34 UTC, Rullflex commented on src/pages/profile/edit/index.vue
>      <h5 class="q-mb-lg q-mx-lg">Редактирование профиля</h5>
ошибка в верстке: 8px + 24px с боков

2024-07-12 11:34 UTC, Rullflex commented on src/pages/profile/edit/ui/ChangeAvatarSection.vue
> +  console.log('click');
console.log, даже линтер на это жалуется

2024-07-12 11:34 UTC, Rullflex commented on src/pages/profile/edit/ui/ProfileEditDialog.vue
> +  isDialogVisible.value = false;
тут по-другому можно сделать, когда надо закрыть модалку ты эмитишь event close - снаружи у тебя на компоненте `@close="isDialogVisible = false"` и `v-if="isDialogVisible"`. Это ты избавишься от `isDialogVisibleModel`.

2024-07-12 11:34 UTC, Rullflex commented on src/pages/profile/edit/ui/ProfileEditDialog.vue
> +  dialogModel.value = '';
Дальше, раз у тебя при открытии каждый раз модалка заново рендерится тебе не надо будет очищать `dialogModel`

2024-07-12 11:34 UTC, Rullflex commented on src/pages/profile/edit/ui/ProfileEditDialog.vue
> +const dialogModel = defineModel('model', { default: '' });
Ну а стор ты обновляешь внутри, и тебе не надо возвращать  `dialogModel`

2024-07-12 11:34 UTC, Rullflex commented on src/pages/profile/edit/index.vue
> +export type ItemType = 'name' | 'surname' | 'dateOfBirth' | 'email' | 'phone';
лучше этот тип вынести в локальный файл types.ts

2024-07-12 11:34 UTC, Rullflex commented on src/pages/profile/edit/ui/ItemsList.vue
> +    @click="emit('itemClick', item.type)"
ты можешь просто эмит вызывать через `$emit(...)` в шаблоне уже есть этот метод, его не обязательно явно указывать, ты же типов не пропиываешь никакие

2024-07-12 11:34 UTC, Rullflex commented on src/pages/profile/edit/ui/ItemsList.vue
> +const emit = defineEmits(['itemClick']);
а если тип передаваемого значения нужен то указывай его тут

2024-07-12 11:34 UTC, Rullflex commented on src/pages/profile/edit/index.vue
> +export type ItemType = 'name' | 'surname' | 'dateOfBirth' | 'email' | 'phone';
вообще замени это лучше на `enum`

2024-07-13 07:03 UTC, Rullflex commented on src/pages/profile/edit/ui/ProfileEditDialog.vue
> +    case 'phone':
для этих строк тоже можно применить `enum`

2024-07-13 07:04 UTC, Rullflex commented on src/pages/profile/edit/ui/ProfileEditDialog.vue
> +        v-else-if="dialogType === 'email'"
здесь тоже все строковые константы через `enum` определить можно

2024-07-13 07:14 UTC, Rullflex approved these changes
Теперь стало прям песня! особенно компонент самой страницы. Я сделал пару правок и залил

2024-07-13 07:16 UTC, merged